name: Train and Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Python path
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Train models
        run: |
          mkdir -p models
          python training/two_tower.py
          python training/ranking.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Commit and push models
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add models/
          git commit -m "Update trained models" || echo "No changes to commit"
          git push

      - name: Trigger Render deployment
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"