name: Train Model
on:
  workflow_dispatch:  # Manually trigger the workflow
  schedule:
    - cron: '0 0 * * 0'  # Optional: Run weekly at midnight UTC

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python training/two_tower.py  # Run your training script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Use GitHub Secrets

      - name: Commit and push trained model
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add models/  # Add your trained model directory
          git commit -m "Update model from GitHub Actions"
          git push